development:
  adapter: postgresql
  encoding: unicode
  database: recipe_freak_db
  pool: 2
  username: nicklevenson
  password: 

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>